import { useState, useEffect } from 'react'
import Person from './components/Person.jsx'
import Filter from './components/filter.jsx'
import PersonForm from './components/PersonForm.jsx'
import People from './components/People.jsx'
import service from './service/people.js'
import Notification from './components/Notification.jsx'

const App = () => {
  const [persons, setPersons] = useState([])
  const [newName, setNewName] = useState('')
  const [newNumber, setNewNumber] = useState('')
  const [searchName, setNewSearchName] = useState('')
  const [addedPersonMessage, setAddedPersonMessage] = useState('')
  const [notificationType, setNotificationType] = useState('')

  useEffect(() => {
  service
    .getAll()
    .then(people => {
      setPersons(people)
    })
  }, [])


  const handlePersonSubmit = (event) => {
    event.preventDefault()
    const duplicatePerson = persons.find(person => person.name === newName)
    if (duplicatePerson !== undefined){

      if (window.confirm(`${duplicatePerson.name}, is already in the phonbebook, replace the old number with a new one?`)) {
        const updatedPerson = {...duplicatePerson, number: newNumber }
        console.log('updated person', updatedPerson)
        return service
          .update(duplicatePerson.id, updatedPerson)
          .then(updatedPerson => {
            console.log('we are in the promise', updatedPerson)
            setPersons(persons => persons.map(person => person.id === duplicatePerson.id ? updatedPerson : person))
            setNewName('')
            setNewNumber('')
          })
          .catch(error => {
            console.log('we are in the catch', error)
            setAddedPersonMessage(`Information of ${updatedPerson.name} has already been removed from server`)
            setNotificationType('error')
          })
      }
    }

    const nameObject = {
      name: newName,
      number: newNumber,
      // id: persons.length + 1 generated by the server
    }
    service
    .create(nameObject)
    .then(createdPerson => {
      console.log("Inside the post")
      setPersons(persons.concat(createdPerson))
      setAddedPersonMessage(`Added ${createdPerson.name}`)
      setNotificationType('success')
      setNewName('')
      setNewNumber('')
    })
  }

  const removePerson = (id) => {
    console.log(' in remove function')
    const personToRemove = persons.find(person => person.id === id)
    console.log('person to remove', personToRemove)
    if (window.confirm("Delete " + personToRemove.name + " ?")) {
      
      service
      .deletePerson(id, personToRemove)
      .then(removedPerson => {
        setPersons(persons.filter(person => person.id !== id))
      })
    }
  }

  const namesToShow = searchName
    ? persons.filter(person => person.name.toLowerCase().includes(searchName.toLowerCase()))
    : persons

  return (
    <div>
      <h2>Phonebook</h2>
      <Notification message={addedPersonMessage} type={notificationType}/>
      <Filter searchName={searchName} setSearchName={setNewSearchName}/>

      <h3>add a new</h3>
      <PersonForm handlePersonSubmit={handlePersonSubmit} newName={newName} newNumber={newNumber} 
      setNewName={setNewName} setNewNumber={setNewNumber}/>

      <h2>Numbers</h2>
      <People persons={namesToShow} deleteHandler={removePerson}/>
    </div>
  )
}

export default App